# Generated by Django 2.2.6 on 2019-12-01 11:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_code', models.CharField(max_length=10)),
                ('position', django_enumfield.db.fields.EnumField(default=0, enum=member.models.Position)),
                ('mobile_number', models.CharField(max_length=11)),
                ('kudos', models.IntegerField(default=0)),
                ('available_point', models.IntegerField(default=0)),
                ('kpi_rate', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', django_enumfield.db.fields.EnumField(default=0, enum=member.models.Rules)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Members')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Members')),
                ('members', models.ManyToManyField(related_name='memberteam', through='member.Membership', to='member.Members')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('member', 'team')},
        ),
    ]
