# Generated by Django 2.2.6 on 2019-10-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
    ]
