# Generated by Django 2.2.6 on 2019-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_membership_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
