# Generated by Django 2.2.6 on 2019-11-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20191023_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='tel',
        ),
        migrations.AddField(
            model_name='members',
            name='mobile_number',
            field=models.CharField(default=967686, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='national_code',
            field=models.CharField(default=87576, max_length=10),
            preserve_default=False,
        ),
    ]
