# Generated by Django 2.2.6 on 2019-10-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20191020_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='point',
            new_name='available_point',
        ),
    ]
