# Generated by Django 2.2.6 on 2019-10-23 08:42

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import kpi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KpiForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=kpi.models.Status)),
                ('avarage', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KpiRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, null=True)),
                ('key', models.IntegerField(null=True)),
                ('kpi_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rateform', to='kpi.KpiForm')),
            ],
        ),
    ]
