# Generated by Django 2.2.6 on 2019-10-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpi', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiform',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpiformmember', to='member.Members'),
        ),
        migrations.AddField(
            model_name='kpiform',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpiformsubmittedby', to='member.Members'),
        ),
        migrations.AddField(
            model_name='kpiform',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpiformteam', to='member.Team'),
        ),
    ]
