# Generated by Django 2.2.6 on 2019-10-15 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpiform',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpiformmember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpiform',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpiformsubmittedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpiform',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpiformteam', to='member.Team'),
        ),
    ]
