# Generated by Django 2.2.6 on 2019-10-15 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_auto_20191015_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpiform',
            name='avarage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpiform',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpiformsubmittedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
