# Generated by Django 2.2.6 on 2019-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kudos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('from_member_available_point', models.IntegerField()),
                ('to_member_kudos', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
