# Generated by Django 2.2.6 on 2019-10-15 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kodus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudos',
            name='from_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudosfrom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kudos',
            name='to_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudosto', to=settings.AUTH_USER_MODEL),
        ),
    ]
