# Generated by Django 2.2.6 on 2019-10-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodus', '0002_auto_20191015_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kudos',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
